### ISSUE TITLE
Can't import demo content

### ISSUE THREAD

**Issue by cristian-e** [ColorlibHQ/repair#1]
I can't import any demo content for this theme. Using the `One Click Demo Import` plugin, I get this error.

![999](https://user-images.githubusercontent.com/43263346/53093444-1dff3180-3520-11e9-9d28-b731968c9c08.PNG)

**Comment by codepixar** [comment]
We are working on this issue update soon..

**Comment by codepixar** [comment]
Fixed in v1.0.1
